parameters:
    kernel.secret: yoursecretshouldbehere
    app_path: "../.."

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: false

event_bus:
    exchanges:
        events: events
    router:
        _all: events
    async_pass_through: false
    async_adapter:
        adapter: amqp
        amqp:
            host: rabbitmq

# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Domain\Model\User\InMemoryUserRepository:
# DBAL\Model\User\DBALUserRepository:
    Domain\Model\User\UserRepository:
        alias: Domain\Model\User\InMemoryUserRepository

    #
    # Controllers
    #
    App\Controller\:
        resource: "%app_path%/src/Controller/*"
        tags:
            - {name: controller.service_arguments}

    Domain\QueryHandler\:
        resource: "%app_path%/src/Domain/QueryHandler/*"
        tags: ['query_handler']

    Domain\CommandHandler\:
        resource: "%app_path%/src/Domain/CommandHandler/*"
        tags: ['command_handler']

    Domain\EventSubscriber\:
        resource: "%app_path%/src/Domain/EventSubscriber/*"
